/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jmonkey_test;

import com.jme3.system.AppSettings;
import jmonkey_test.settings.GameSettings;
import org.junit.jupiter.api.Test;

class SettingsTest {

    @Test void testSettings() {
        SettingsApp app = new SettingsApp();

        AppSettings settings = new GameSettings().loadOrDefault();
        app.setSettings(settings);

        app.start();
    }
}
