/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jmonkey_test;

import com.jme3.app.SimpleApplication;
import com.jme3.material.Material;
import com.jme3.math.ColorRGBA;
import com.jme3.scene.Geometry;
import com.jme3.scene.shape.Box;
import com.jme3.system.AppSettings;
import jmonkey_test.settings.GameSettings;

public class App extends SimpleApplication {

    public static void main(String[] args) {

        App app = new App();

        AppSettings settings = new GameSettings().loadOrDefault();
        app.setSettings(settings);

        app.start();

    }

    @Override
    public void simpleInitApp() {

        Box b = new Box(1, 1, 1);
        Geometry geom = new Geometry("Box", b);

        Material mat = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        mat.setColor("Color", ColorRGBA.Blue);
        geom.setMaterial(mat);

        rootNode.attachChild(geom);

    }

    @Override
    public void simpleUpdate(float tpf) {
        //TODO: add update code
    }

    public Object getGreeting() {
        return new Object();
    }
}
